spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #클래스 변수명 그대로 테이블이 생성한다.
      use-new-id-generator-mappings: false  #JPA 전략을 사용하지 않고 커넥션하는 데이터베이스 auto increment 전략을 그래도 사용한다.
    properties:
      hibernate:
        show_sql: true

  jackson: #Lazy-loading으로 인해 empty-beans이 생길 수 있을때 예외처리 해주는 옵션이다.
    serialization:
      fail-on-empty-beans: false

  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html

oauth:
  kakao:
    authorize : https://kauth.kakao.com/oauth/authorize
    client_id : b513d8919eb20fb7c475f7474c840680
    redirect_uri : http://localhost:8080/auth/kakao/callback
    oauth_token : https://kauth.kakao.com/oauth/token
    user_into : https://kapi.kakao.com/v2/user/me
  oauthkey: 1qazxsw2

logging.level:
  org.hibernate.SQL: debug